config/routes.rb
AncoraDeCarreira::Application.routes.draw do
  resources :questions_anwers

  scope :api do
    get "/answers(.:format)" => "answers#index"
    post "/answers(.:format)" => "answers#create"
  end

  get "say/hello"
  get "say/goodbye"
  root "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :question_answers
  validates_presence_of :name, :email, :institution, :course, :final_result
  accepts_nested_attributes_for :question_answers

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @answers = Answer.all

    #respond_to do |format|
     # format.csv { send_data @answers.as_csv }
    #end
    #send_data @answers.as_csv

    hash_to_excel_csv @answers.as_csv, "ancoras"
  end
  
  def hash_to_excel_csv(data, filename)
    send_data data.encode(Encoding::ISO_8859_1, :undef => :replace),
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}.csv"

  end

  def create
    @answer = Answer.new(answer_params)
    puts params
    @answer.save
    render :json => {'Message' => 'Successfully created #{answer.name}'}.to_json, :status => 200
  end

  private
  def answer_params
    params.require(:answer).permit!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_anwers_controller.rb
class QuestionsAnwersController < ApplicationController
  before_action :set_questions_anwer, only: [:show, :edit, :update, :destroy]

  # GET /questions_anwers
  # GET /questions_anwers.json
  def index
    @questions_anwers = QuestionsAnwer.all
  end

  # GET /questions_anwers/1
  # GET /questions_anwers/1.json
  def show
  end

  # GET /questions_anwers/new
  def new
    @questions_anwer = QuestionsAnwer.new
  end

  # GET /questions_anwers/1/edit
  def edit
  end

  # POST /questions_anwers
  # POST /questions_anwers.json
  def create
    @questions_anwer = QuestionsAnwer.new(questions_anwer_params)

    respond_to do |format|
      if @questions_anwer.save
        format.html { redirect_to @questions_anwer, notice: 'Questions anwer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @questions_anwer }
      else
        format.html { render action: 'new' }
        format.json { render json: @questions_anwer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions_anwers/1
  # PATCH/PUT /questions_anwers/1.json
  def update
    respond_to do |format|
      if @questions_anwer.update(questions_anwer_params)
        format.html { redirect_to @questions_anwer, notice: 'Questions anwer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @questions_anwer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions_anwers/1
  # DELETE /questions_anwers/1.json
  def destroy
    @questions_anwer.destroy
    respond_to do |format|
      format.html { redirect_to questions_anwers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questions_anwer
      @questions_anwer = QuestionsAnwer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questions_anwer_params
      params[:questions_anwer]
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_anwers_helper.rb
module QuestionsAnwersHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Share - Âncoras de Carreira</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="ancora">
<%= yield %>

</body>
</html>

app/views/questions_anwers/_form.html.erb
<%= form_for(@questions_anwer) do |f| %>
  <% if @questions_anwer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questions_anwer.errors.count, "error") %> prohibited this questions_anwer from being saved:</h2>

      <ul>
      <% @questions_anwer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions_anwers/edit.html.erb
<h1>Editing questions_anwer</h1>

<%= render 'form' %>

<%= link_to 'Show', @questions_anwer %> |
<%= link_to 'Back', questions_anwers_path %>

app/views/questions_anwers/index.html.erb
<h1>Listing questions_anwers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions_anwers.each do |questions_anwer| %>
      <tr>
        <td><%= link_to 'Show', questions_anwer %></td>
        <td><%= link_to 'Edit', edit_questions_anwer_path(questions_anwer) %></td>
        <td><%= link_to 'Destroy', questions_anwer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questions anwer', new_questions_anwer_path %>

app/views/questions_anwers/new.html.erb
<h1>New questions_anwer</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_anwers_path %>

app/views/questions_anwers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_questions_anwer_path(@questions_anwer) %> |
<%= link_to 'Back', questions_anwers_path %>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<h1>Aloooo</h1>
<p>It is now <%= @time %></p>